FROM oven/bun:1 AS build
WORKDIR /app
ARG NPM_AUTH_TOKEN
ENV NPM_AUTH_TOKEN=$NPM_AUTH_TOKEN
COPY package.json bun.lock .npmrc ./
RUN bun install --frozen-lockfile
COPY . .
RUN bun run docs:build

FROM nginx:1.27-alpine AS runner
COPY --from=build /app/dist/docs /usr/share/nginx/html
COPY docs-nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
